### ISSUE TITLE
Example usage?

### ISSUE THREAD

**Issue by lolz0r** [anoidgit/Convolution-in-RNN#1]
Hi,
Is would be great is there was a simple example of how to use these layers. Specifically the nn argument within the layer constructor; the passed in conv layer will be wrapped within the LSTM/CONV system?

**Comment by hfxunlp** [comment]
I have some code for sequence classification task like chinese word segmentation long before, I want to use convolution neural network to learn features used for gru so I use these code to put the convolution neural network in GRU and LSTM, but it is very very slow, because there are a lot of redundent(repeat) computation in it. If you want combine them, my advise is just stack the convolution and RNN, maybe there are some module like narrow between them.
